version: '2'
services:
  commanderserver:
    depends_on:
      - db
      - zoo1
    image: holywen/commanderserver:${TAG}
    hostname: commanderserver
    ports:
      - 8000
      - 8443
      - 61613
    volumes:
      - ./plugins:/opt/electriccloud/electriccommander/plugins
      - ./workspace:/opt/electriccloud/electriccommander/workspace
      - ./conf:/opt/electriccloud/electriccommander/conf
      - ./conf/tmp1:/opt/electriccloud/electriccommander/conf/tmp
      - ./logs/server:/opt/electriccloud/electriccommander/logs
      
  commanderserver2:
    depends_on:
      - db
      - commanderserver
    image: holywen/commanderserver:${TAG}
    hostname: commanderserver2
    ports:
      - 8000
      - 8443
      - 61613
    volumes:
      - ./plugins:/opt/electriccloud/electriccommander/plugins
      - ./workspace:/opt/electriccloud/electriccommander/workspace
      - ./conf:/opt/electriccloud/electriccommander/conf
      - ./conf/tmp2:/opt/electriccloud/electriccommander/conf/tmp
      - ./logs/server2:/opt/electriccloud/electriccommander/logs

  commanderserver3:
    depends_on:
      - db
      - commanderserver
    image: holywen/commanderserver:${TAG}
    hostname: commanderserver3
    ports:
      - 8000
      - 8443
      - 61613
    volumes:
      - ./plugins:/opt/electriccloud/electriccommander/plugins
      - ./workspace:/opt/electriccloud/electriccommander/workspace
      - ./conf:/opt/electriccloud/electriccommander/conf
      - ./conf/tmp3:/opt/electriccloud/electriccommander/conf/tmp
      - ./logs/server3:/opt/electriccloud/electriccommander/logs
      
  commanderapache:
    depends_on:
      - commanderserver
    image: holywen/commanderapache:${TAG}
    hostname: commanderapache
    ports:
      - 80
      - 443
    volumes:
      - ./plugins:/opt/electriccloud/electriccommander/plugins
      - ./workspace:/opt/electriccloud/electriccommander/workspace
      
  localagent:
    depends_on:
      - commanderserver
    image: holywen/commanderagent:${TAG}
    hostname: localagent
    ports:
      - 6800
      - 7800
    volumes:
      - ./plugins:/opt/electriccloud/electriccommander/plugins
      - ./workspace:/opt/electriccloud/electriccommander/workspace

  repository:
    image: holywen/commanderrepository:${TAG}
    hostname: repository
    ports:
      - 8200
    volumes:
      - ./plugins:/opt/electriccloud/electriccommander/plugins
      - ./workspace:/opt/electriccloud/electriccommander/workspace
      - ./repository-data:/opt/electriccloud/electriccommander/repository-data
      
  db:
     image: mysql:5.7
     volumes:
       - ./db-data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ecdb
       MYSQL_DATABASE: ecdb
       MYSQL_USER: ecdb
       MYSQL_PASSWORD: ecdb

  zoo1:
    image: zookeeper
    hostname: zoo1
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./zoo/zoo1:/data
      
  zoo2:
    image: zookeeper
    hostname: zoo2
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./zoo/zoo2:/data
      
  zoo3:
    image: zookeeper
    hostname: zoo3
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./zoo/zoo3:/data

  haproxy:
    image: haproxy
    hostname: haproxy
    ports:
      - 80:80
      - 443:443
      - 8000:8000
      - 8443:8443
      - 61613:61613
      - 1936:1936
    volumes:
      - ./haproxy/:/usr/local/etc/haproxy/
