version: '2'

services:
  commanderserver:
    extends:
      file: common-services.yml
      service: commanderserver
    depends_on:
      - db
      - zookeeper1
    hostname: commanderserver
    volumes:
      - ./conf/tmp1:/opt/electriccloud/electriccommander/conf/tmp
      - ./logs/server:/opt/electriccloud/electriccommander/logs
      
  commanderserver2:
    extends:
      file: common-services.yml
      service: commanderserver
    depends_on:
      - db
      - commanderserver
    hostname: commanderserver2
    volumes:
      - ./conf/tmp2:/opt/electriccloud/electriccommander/conf/tmp
      - ./logs/server2:/opt/electriccloud/electriccommander/logs

  commanderserver3:
    extends:
      file: common-services.yml
      service: commanderserver
    depends_on:
      - db
      - commanderserver
    hostname: commanderserver3
    restart: always
    volumes:
      - ./conf/tmp3:/opt/electriccloud/electriccommander/conf/tmp
      - ./logs/server3:/opt/electriccloud/electriccommander/logs
      
  commanderapache:
    extends:
      file: common-services.yml
      service: commanderapache
    depends_on:
      - commanderserver
    hostname: commanderapache
      
  localagent:
    extends:
      file: common-services.yml
      service: commanderagent
    depends_on:
      - commanderserver
    hostname: localagent

  repository:
    extends:
      file: common-services.yml
      service: commanderrepository
    hostname: repository
      
  db:
    extends:
      file: common-services.yml
      service: mysql
    hostname:
      db

  zookeeper1:
    extends:
      file: common-services.yml
      service: zookeeper
    hostname: zookeeper1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - ./zoo/zookeeper1:/data
      
  zookeeper2:
    extends:
      file: common-services.yml
      service: zookeeper
    hostname: zookeeper2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - ./zoo/zookeeper2:/data
      
  zookeeper3:
    extends:
      file: common-services.yml
      service: zookeeper
    hostname: zookeeper3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - ./zoo/zookeeper3:/data

  haproxy:
    extends:
      file: common-services.yml
      service: haproxy

