version: '2'

services:
  commanderserver:
    extends:
      file: common-services.yml
      service: commanderserver
    depends_on:
      - db
      - zookeeper1
    labels:
        - "interlock.hostname=commanderserver"
        - "interlock.domain=local"
      
  commanderapache:
    extends:
      file: common-services.yml
      service: commanderapache
    depends_on:
      - commanderserver
      
  localagent:
    extends:
      file: common-services.yml
      service: commanderagent
    depends_on:
      - commanderserver

  repository:
    extends:
      file: common-services.yml
      service: commanderrepository
      
  db:
    extends:
      file: common-services.yml
      service: mysql

  zookeeper1:
    extends:
      file: common-services.yml
      service: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - ./zoo/zookeeper1:/data
      
  zookeeper2:
    extends:
      file: common-services.yml
      service: zookeeper
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - ./zoo/zookeeper2:/data
      
  zookeeper3:
    extends:
      file: common-services.yml
      service: zookeeper
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - ./zoo/zookeeper3:/data

  interlock:
    image: ehazlett/interlock:master
    command: run -c /etc/interlock/config.toml
    volumes:
        - ./interlock/config.toml:/etc/interlock/config.toml
        - ./interlock/haproxy.cfg.template:/usr/local/etc/interlock/haproxy.cfg.template
        - /var/run/docker.sock:/var/run/docker.sock
       
  haproxy:
    extends:
      file: common-services.yml
      service: haproxy
    labels:
        - "interlock.ext.name=haproxy"
    links:
        - interlock:interlock
    depends_on:
        - interlock
        - commanderserver

